apiVersion: v1
kind: Service
metadata:
  name: iris-api-svc
spec:
  type: LoadBalancer
  selector:
    app: iris-api
  ports:
  - port: 80          # external port
    targetPort: 8200  # container port

